// <auto-generated />
namespace DoSomething.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeusertablename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeusertablename));
        
        string IMigrationMetadata.Id
        {
            get { return "201407171013101_change-user-table-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
